services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: membership
      POSTGRES_USER: membership
      POSTGRES_PASSWORD: membership
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
